# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: ubuntu:16.04
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
      ZK_BUILD_NUMBER: 3.5.5-badh1
      HADOOP_BUILD_NUMBER: 2.8.4-badh1
      IGNITE_BUILD_NUMBER: 2.6.0-badh1
    
    steps:
      - run: apt-get update && apt-get upgrade -y && apt-get install -y git curl

      - checkout

      # Download and cache dependencies
      #- restore_cache:
      #    keys:
      #    # fallback to using the latest cache if no exact match is found
      #    - v1-dependencies-

      - run: apt-get install -y maven openjdk-8-jdk python-pip
      - run: pip install awscli
      - run: aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - run: aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - run: aws configure set default.region eu-west-1
      - run: aws s3 cp s3://mvn.barbarians.io/zookeeper-$ZK_BUILD_NUMBER-bin.jar /tmp
      - run: aws s3 cp s3://mvn.barbarians.io/zookeeper-$ZK_BUILD_NUMBER-test.jar /tmp
      - run: mvn install:install-file -Dfile=/tmp/zookeeper-$ZK_BUILD_NUMBER-bin.jar -DgroupId=org.apache.zookeeper -DartifactId=zookeeper -Dversion=$ZK_BUILD_NUMBER -Dpackaging=jar
      - run: mvn install:install-file -Dfile=/tmp/zookeeper-$ZK_BUILD_NUMBER-test.jar -DgroupId=org.apache.zookeeper -DartifactId=zookeeper -Dversion=$ZK_BUILD_NUMBER -Dclassifier=tests -Dpackaging=test-jar
      - run: aws s3 cp --recursive s3://mvn.barbarians.io/hadoop/m2 ~/.m2

      - run: mvn clean install package dependency:go-offline -Prelease -Dignite.edition=hadoop -DskipTests -Dhadoop.version=$HADOOP_BUILD_NUMBER -Dzookeeper.version=$ZK_BUILD_NUMBER -Dignite.version=$IGNITE_BUILD_NUMBER

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
        
      # run tests!
      # - run: mvn test -Prelease -Dignite.edition=hadoop -DskipTests -Dhadoop.version=2.8.4

      - run: aws s3 cp --recursive ~/.m2 s3://mvn.barbarians.io/ingite/m2
      - run: aws s3 cp /root/repo/target/bin/apache-ignite-hadoop-$IGNITE_BUILD_VERSION-bin.zip s3://mvn.barbarians.io

      #- store_artifacts:
      #    path: /home/circleci/repo/target/bin/apache-ignite-hadoop-2.6.0-badh1-bin.zip
      #    destination: badh-ignite-bin

